### ISSUE TITLE
orion list is not showing all experiments

### ISSUE THREAD

**Issue by mariam-jamal** [Epistimio/orion#1101]
**Describe the bug**
When I run orion list to list all the experiments, it gives some error and does not display all the experiments

**Expected behavior**
Should list all the experiments

**Steps to reproduce**
Describe the steps to reproduce the bug, if applicable:

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Python version: [e.g. 3.7]
 - Oríon version: [e.g. 0.1.7]
 - Database: [e.g. PickleDB, MongoDB]
 Python: 3.9
 Orion:  0.2.6.post315+gefe60756
 Database: PickleDB

**Additional context**
If applicable, attach any log of screenshots that can help explain the problem.
I switched from an orion version 0.2.4 to the 0.2.6, so the python api was a bit different
<img width="851" alt="image" src="https://github.com/Epistimio/orion/assets/30799589/0743bd95-6f01-4352-87f0-1ea9bae48e7b">
I also checked if the db is configured properly or not, and it was

**Comment by bouthilx** [comment]
Hi, sorry for the long delay!

Could you please share your configuration and the version of Oríon you were using. I'll need it to try reproducing this issue with the algo EvolutionaryES. 

Thank you!

**Comment by mariam-jamal** [comment]
Ok, so I managed to solve this issue.
As seen on line 235 in evolution_es.py:
mod_name, func_name = function_string.rsplit(".", 1)
Here, due to version mismatch, the mod_name and func_name was splitting differently, which led to the error. By fixing it correctly, I was able to solve it.
**mod_name, func_name = "orion.algo.evolution_es.mutate_functions", "default_mutate"**
<img width="690" alt="image" src="https://github.com/Epistimio/orion/assets/30799589/f90d3b52-fe1a-4895-943f-d2243e42011c">
