### ISSUE TITLE
Support for templates for positional arguments

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [Epistimio/orion#119]
It makes sense to allow template positional arguments with variables such as `trial.full_name`. (Discussed with @bouthilx )

Connected to #118

**Comment by bouthilx** [comment]
Thanks for the feature request!

We will look into this shortly, but it will probably be after ICML since we will all be there.

**Comment by fosterrath-mila** [comment]
Should we close this ?

**Comment by DatCorno** [comment]
This has been added with #172.

**Comment by bouthilx** [comment]
Thanks!
