### ISSUE TITLE
Use `argcomplete` for tab completion in shell

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [Epistimio/orion#122]
Have you considered to use http://argcomplete.readthedocs.io/en/latest/ ? This project looks very nice.

**Comment by bouthilx** [comment]
Yes indeed! Autocompletion on the experiment names would be very handy! I looked into it while searching for command line arguments autocompletion a few weeks ago but didn't have time to get into the details. I'll comment further in your PR.

**Comment by Thomsch** [comment]
When we work on this feature, a new issue will be created.
