### ISSUE TITLE
Request experiment status from command line

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [Epistimio/orion#125]
Proposal: add a new subcommand `orion status -n <name>`. It should output the experiment information: best objective so far, total number of trials, number of trials finished, etc.

**Comment by bouthilx** [comment]
I implemented a prototype for ```orion info``` and updated the example accordingly. I added sections ```Commandline``` and ```Space```.

**Comment by bouthilx** [comment]
A year later, we finally have the 3 commands merged in develop. They should be soon released in v0.1.5 (end of week).

- list in #208
- status in #222 
- info in #211 

Sorry for the terrible delay. The project stalled from septembre 2018 to may 2019 but we are back on it and it won't stall again. :)
