### ISSUE TITLE
"Core" section in documentation should be "Installation"

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [Epistimio/orion#132]
Looks like a wrong link in the docs: http://orion.readthedocs.io/en/latest/installing.html

**Comment by bouthilx** [comment]
The title is misleading indeed. It's about the installation of the core. There would be installation of core, installation of database, and installation of plugins.

**Comment by dmitriy-serdyuk** [comment]
I see now, there is a pale grey "INSTALLATION GUIDE" title, but it is hard to read.

**Comment by bouthilx** [comment]
Done a while ago in #134
