### ISSUE TITLE
Writing an sqlite db interface

### ISSUE THREAD

**Issue by angeloskath** [Epistimio/orion#147]
Hello all,

I started writing an sqlite db implementation for Orion. It currently is in working state but I need to add tests, improve comments etc. When I do those I will do a pull request.

It is not an issue that I am reporting, more an attempt to start a conversation around developing new db implementations and the design decisions that have been made and make it harder to implement a db connector for databases other than MongoDB.

The application assumes in many places that the database is MongoDB. That makes for a leaky interface because the required interface is not the one in orion.core.io.database.AbstractDB but implicitly defined by the inner workings of pymongo and MongoDB. A non-exhaustive list of the above follows:

- assume schema-less document structure
- assume primary keys in the '_id' field
- assume primary keys to be text
- query using the MongoDB query language as implemented by pymongo

I believe that regardless of whether that decision (for a leaky interface) is good or bad the above cases should be documented so that people know what they need to implement. I can also contribute in this.

Regarding sqlite and relational databases I think that we could create a generic implementation that makes it infinitely easier to implement new RDBMSs into Orion by dealing with ids, unstructured dictionarys, indexes in documents etc in a generic way.

I hope this colorless wall of text didn't come off as harsh or useless, it was meant as a conversation starter.

Cheers,
Angelos

**Comment by DatCorno** [comment]
This is something that has been in the back of my mind for a long time but I never got around to doing it. I'd be happy to hear your ideas regarding possible solutions to the points you raise.

**Comment by bouthilx** [comment]
Hi Angelos! 

I'm glad you raised this issue and I would love to discuss it in greater details. I believe this discussion would be a better fit to Discourse than a github issue, but it's good to have an issue linked to it.

I opened a new thread and wrote my comment in our Discourse [here](https://discourse-epistimio.mila.quebec/t/orion-generic-database-interface/48).

Thanks again!

**Comment by bouthilx** [comment]
I will close this issue since the discussion ended a long time ago. Feel free to re-open it if you would like to work on this again. :)
