### ISSUE TITLE
Fix OS application directories to work with virtualenvs

### ISSUE THREAD

**Issue by tsirif** [Epistimio/orion#16]
Fix `metaopt.utils._appdirs` to be able to return correct OS specific application directories for the case that Python lives in a virtual environment.

For *nix, it works perfectly.
For OS X: A fix code for `AppDirs.site_data_dir` is provided at tsirif@095b0d7, in branch [`fix/appdirs`](https://github.com/tsirif/metaopt/tree/fix/appdirs).

Implement and check correctness for:
- [ ] OS X
- [ ] Windows

This is a bug, if we consider our software to be installable in these OS as well.

As a note: site directory should be contained within the *active* (which Python runs at a time the `_appdirs` module) Python's install prefix directory. So that, for the data directory, this would be `sys.prefix`+`share[/appname[/version]]` mostly and if `sys.prefix` is the system site, then choose OS specific data dir.

**Comment by dendisuhubdy** [comment]
Ok so the thing is @tsirif that most OS X users like me probably use `brew install python` to install python in their system, and you would probably always need a `sudo` to install a python package unless you would use `anaconda`. 

The thing is, the test that we did yesterday was that even within the `anaconda` environment, we have not been able to install it without `sudo`. Weird.

**Comment by tsirif** [comment]
If our package is to be system-installed via `brew` for example, then `data_site_dir` is correctly set and `sudo` is justifiably asked for. But as there are virtual environments like anaconda, it should be more smart and check where it should install the files.

**Comment by bouthilx** [comment]
@tsirif Do you remember if that was properly fixed by #22 or something was missing?

**Comment by bouthilx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix OS application directories to work with virtualenvs](https://trello.com/c/6V9hdnZj/238-fix-os-application-directories-to-work-with-virtualenvs)
