### ISSUE TITLE
Broken link to installation guide

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [Epistimio/orion#162]
The link in README.rst is broken: `https://orion.readthedocs.io/en/latest/installing.html`

Also, it would be cool to put a link to documentation right in the repo description (check out https://github.com/numpy/numpy)
![screen shot 2019-02-25 at 2 03 59 pm](https://user-images.githubusercontent.com/2872615/53361683-516a0380-3906-11e9-8ab2-ff640b3f280a.png)

**Comment by bouthilx** [comment]
Agreed! I added the link at the top. I'll fix the link soon, or you are very welcome if you would like to do it. :) Thanks!
