### ISSUE TITLE
Less logging about lock acquired/released.

### ISSUE THREAD

**Issue by mirkobronzi** [Epistimio/orion#199]
Hello,
I was wondering if the logging level for
`INFO:filelock:Lock 47831344220032 acquired on ...`
could be lowered a bit? (maybe DEBUG?)

On my side, the log file is full of these lines..

Thanks,
Mirko

**Comment by bouthilx** [comment]
I agree INFO is too high. I would even push it down below DEBUG if I could. :) Do you have solution that you could contribute in a PR?

**Comment by mirkobronzi** [comment]
This is a possible solution:
https://github.com/Epistimio/orion/pull/201

Given the logging is inside the filelock module, and we do not want to modify that, the idea is to set the logging to that module to ERROR, so that INFO does not print.

W.r.t. putting this lines in __init__.py, it comes from a suggestion here:
https://docs.python-guide.org/writing/logging/

See: `Here is an example of best practice from the requests source – place this in your __init__.py:`

Let me know if you think this should be done differently/elsewhere.

**Comment by bouthilx** [comment]
Thanks a lot! I think it makes more sense to place it in the only module it is used in this case. In the given example they talk about the global logger of a package. Here it is more about a third-party logger that is used only in one of our modules.

**Comment by mirkobronzi** [comment]
Right - just modified the code.

**Comment by mirkobronzi** [comment]
fixed in #201
