### ISSUE TITLE
Fully test support for DB(uri)

### ISSUE THREAD

**Issue by bouthilx** [Epistimio/orion#29]
Unit tests currently cover ```mongodb://user:pass@url/database``` only. We need to test many different ways.

For instance:
```mongodb://url```
```mongodb://url/database```
```mongodb://url:port/database```
```mongodb://user:pass@url```
```mongodb://user:pass@url/database```
```mongodb://user:pass@url/database?someOptions=someValue?someOtherOption=SomeOtherValue```

We wouldn't have to test all this if we simply had passed URI without extracting the parameters and passing them separately to MongoClient.

I don't think we need those tests right now but we need to keep that in mind, hence the issue.

**Comment by tsirif** [comment]
It's kinda gray box testing. Options are not supported yet either ways.

**Comment by bouthilx** [comment]
Sure, those unit tests should not be added now. And suppose we don't have support for options when we _publicize_ the first MVP then we would add all unit-tests except those for options. But given how the mongodb is set up in the lab (I've been using it for another project), we will need to support options before we _publicize_ the MVP in the lab otherwise we won't be able to use it.

**Comment by bouthilx** [comment]
We are migrating to a different storage backend so these tests probably won't ever be needed.
