### ISSUE TITLE
Test good connections with DB(parameters)

### ISSUE THREAD

**Issue by bouthilx** [Epistimio/orion#30]
We have ```test_connection_with_uri``` and ```test_overwrite_uri```, but there is no ```test_connection_with_args```.

**Comment by tsirif** [comment]
@bouthilx oh this is the texture `moptdb`! :) Do you want me to make an explicit one?

**Comment by bouthilx** [comment]
Yeah I think it would be better to make it more explicit.

**Comment by bouthilx** [comment]
We are migrating to a different storage backend so these tests probably won't ever be needed.
