### ISSUE TITLE
Hyperband & Orion Python API does not work well

### ISSUE THREAD

**Issue by Delaunay** [Epistimio/orion#324]

**Comment by bouthilx** [comment]
Do you remember what was this about? Was it because of the `hash_params` or something else?

**Comment by Delaunay** [comment]
* there is no feed back when it is waiting for trials versus the HPO is done
* there is an implicit need to accept trials after sampling (observe with None as result)

I would have to run Olympus but find out if that is all

First point I think was addressed in previous MR.
Second point should be addressed with stateful algo

**Comment by bouthilx** [comment]
I will close this issue since second point is detailed in #357, #358, #359.
