### ISSUE TITLE
Worker termination criteria

### ISSUE THREAD

**Issue by tsirif** [Epistimio/orion#33]
I refer from @bouthilx concerns pointed out on #21.

Algorithms should be provided with an interface to give out their own worker termination criteria.

So far, there is only a criterion from `Experiment` class, i.e. `Experiment.is_done`, which checks whether
the number of completed trials exceeds `Experiment.max_trials` (which comes from configuration).

What else could we expect to have here that make sense in a distributed and asynchronous setting?
Discussion for 13/12/2017 meeting.
@nouiz @lamblin @dendisuhubdy

**Comment by tsirif** [comment]
13/12/2017 Meeting
---------------------------

We discussed possible termination criteria and where the criteria should be asked for and when they are applied. We noticed 2 categories of termination criteria:

1. **User's desires**: Criteria dependent on the user's desire for how much optimization is needed
    - [x] Whether *completed* trials have succeeded a *max_trials* limit. *max_trials* is given through metaopt configuration; default value is "infinite", which would mean that termination is left either on another criterion or is due to external reason (e.g. someone killed the worker).
    - [ ] Whether *best_evaluation* is below (or above - if maximizing) a certain *evaluation_goal* threshold. *evaluation_goal* is given through metaopt configuration; default value is "infinite", which would mean reach as low (or as high - if maximizing) as possible.
2. **Algorithm's desires**: Relative stopping criteria after which a specific algorithm cannot propose any more trials that can have an impact to the procedure.
    - [ ] Algorithms should implement a property to enable them to complain whether it is meaningful (according to the algorithm itself) to continue suggesting new trials or not.

**Comment by bouthilx** [comment]
I believe this discussion is done for now.
