### ISSUE TITLE
How to analyse the result

### ISSUE THREAD

**Issue by GELIELEO** [Epistimio/orion#334]
The section of Analyse and visulization is empty, how can I analyse the results?

**Comment by bouthilx** [comment]
Yes we are about to remove this section until we have visualizations implemented in Oríon. Sorry for the confusion.
For now you can look at commands to get simple monitoring here: https://orion.readthedocs.io/en/latest/user/monitoring.html
Or more specifically the library API if you want to extract your results to visualize them with matplotlib for example: https://orion.readthedocs.io/en/latest/user/monitoring.html#library-api.

**Comment by GELIELEO** [comment]
Thanks for your reply and I got it. @bouthilx , I have  another question: How to manage the experments such as deleting some experiments

**Comment by bouthilx** [comment]
There is currently no support to delete experiments through Oríon directly, you would need to remove them through the dataset backend (mongodb, pickleddb). We had many requests for this feature but did not have time yet to implement it. If you would be interested to contribute it, I'd be happy to help. :)

**Comment by GELIELEO** [comment]
@bouthilx Ok:), well, can you tell how to use the backend of pickleddb, I cannot find any instructions about that so far :O

**Comment by bouthilx** [comment]
```pythonfrom orion.core.io.database.pickleddb import PickledDB

**Comment by bouthilx** [comment]
Here's an example on how you could remove an experiment
```python
from orion.core.io.database import Database
from orion.core.io.experiment_builder import ExperimentBuilder

experiment = ExperimentBuilder().build_view_from({"name": "orion-tutorial"})

# This gets the db singleton that was already instantiated within the experiment object.
db = Database()
# To remove all trials of an experiment
db.remove('trials', dict(experiment=experiment.id))
# To remove the experiment
db.remove('experiments', dict(_id=experiment.id))
```

For more documentation on PickledDB you can look at the code references here: https://orion.readthedocs.io/en/latest/code/core/io/database/pickleddb.html

If you did not create an experiment before (there was no DB singleton created) and you know the experiment id, you could instead do
```python
from orion.core.io.database import Database

# Create the DB
db = PickledDB('/path/to/your/db.pkl)
# To remove all trials of an experiment
db.remove('trials', dict(experiment=experiment_id))
# To remove the experiment
db.remove('experiments', dict(_id=experiment_id))
```
But don't be surprised if you create an experiment and then try to create a PickledDB and get an `orion.core.utils.SingletonAlreadyInstantiatedError`. If you created an experiment, the DB is already created and you can get it with `Database()`.

Please don't hesitate if you have other questions.

**Comment by bouthilx** [comment]
@GELIELEO Did you manage to manage your experiments in the DB?

**Comment by Thomsch** [comment]
The question have been answered 🥇. I'm closing the issue.
