### ISSUE TITLE
Handling job preemption

### ISSUE THREAD

**Issue by hbertrand** [Epistimio/orion#337]
Currently, orion does not handle job that are preempted. It just considers them broken. It would be great if orion could catch that a job is being preempted, and relaunch the same model config next time.

Say you run a search for a 100 models, 10 at a time. In the initial batch, 3 are preempted. The next time a job starts, orion will say `INFO:orion.core.worker:#### Experiment has reached broken trials threshold, terminating.` So you will end up with 7 models instead of 100.

You could raise the default max number of trials, but the broken models will never resume, even if they are good. This is ok for random search but will affect bayesian optimization.

**Comment by bouthilx** [comment]
After online discussion it turns out that the preempted trial was left to status `reserved` as excepted and would have been set to interrupted if it where wasn't many broken trials. The broken trials were due to other issues in the user script (ex: out of memory error).
