### ISSUE TITLE
Warning messages form TRACK

### ISSUE THREAD

**Issue by donglinjy** [Epistimio/orion#348]
If get Track (git+git://github.com/Delaunay/track) installed, orion cli will output some WARNING message as beblow.
[ WARNING] TRACK [20028] track/configuration.py:40 No configuration file found

Guess it comes from here.
```
try:
    from track.client import TrackClient
    from track.persistence.utils import parse_uri
    from track.serialization import to_json
    from track.structure import CustomStatus, Status as TrackStatus
    from track.structure import Project, Trial as TrackTrial, TrialGroup
    from track.persistence.local import ConcurrentWrite
    from track.utils import ItemNotFound

    HAS_TRACK = True
except ImportError:
    REASON = 'Track is not installed'

```

**Comment by Thomsch** [comment]
I get the same messages if Track is installed on develop. In my case, it got installed automatically from using tox to test the application.

**Comment by bouthilx** [comment]
I'm not sure I would categorize this as a bug. Sounds more like an annoying warning on the side of Track. If the fact that no configuration found is not an issue, maybe it should be turned to info instead of warning. But that would be an issue to open in the repo of Track instead of Oríon.

**Comment by bouthilx** [comment]
I will close this for now. If this is causing issues again I suggest we open an issue on Track's repo instead about the warning.
