### ISSUE TITLE
Deprecation warning in resolve_config suggests to write None instead of none into config file

### ISSUE THREAD

**Issue by vmichals** [Epistimio/orion#390]
**Describe the bug**
The deprecation warning raised [here](https://github.com/Epistimio/orion/blob/29c0dfc13637aa3add6a57ce585232d65afcc541/src/orion/core/io/resolve_config.py#L244) when using a config with the following content:
```yaml
algorithms:
    random:
        seed: null
```
suggests to change the config to the following:
```yaml
experiment:
  algorithms: {'random': {'seed': None}}
```
The `None` should be `null` in yaml/json files.

**Expected behavior**
The deprecation warning should show `null` (proper yaml syntax).

**Steps to reproduce**
See the example config in the bug description above

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: 3.6.9
 - Oríon version: 0.1.7
 - Database: PickleDB

**Possible solution**
See PR #391

Instead of calling repr(backward_value) use yaml.dump(backward_value) [here](https://github.com/Epistimio/orion/blob/29c0dfc13637aa3add6a57ce585232d65afcc541/src/orion/core/io/resolve_config.py#L247)

**Comment by Thomsch** [comment]
Thank you for reporting this bug!
We'll take a look at your solution as soon as possible!

Thanks again!
