### ISSUE TITLE
Error message on missing fidelity dimension in ASHA is misleading ("ASHA cannot be used if space does contain a fidelity dimension.")

### ISSUE THREAD

**Issue by vmichals** [Epistimio/orion#392]
**Describe the bug**
The exception raised by ASHA when no fidelity dimension exists says "ASHA cannot be used if space does contain a fidelity dimension."
See [here](https://github.com/Epistimio/orion/blob/29c0dfc13637aa3add6a57ce585232d65afcc541/src/orion/algo/asha.py#L30)

**Expected behavior**
It should say "ASHA can only be used if there is at least one fidelity dimension."

**Steps to reproduce**
It's just a typo in the error message that I stumbled upon while looking for some details about the ASHA implementation.

** Possible solution**
"ASHA cannot be used if space does contain a fidelity dimension." -> "ASHA can only be used if there is at least one fidelity dimension."

**Comment by Thomsch** [comment]
Whoops! Thank you for pointing this problem out!
We'll get to it very soon!

**Comment by bouthilx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Error message on missing fidelity dimension in ASHA](https://trello.com/c/RbRsLyz5/567-error-message-on-missing-fidelity-dimension-in-asha)

**Comment by bouthilx** [comment]
Closed by #402
