### ISSUE TITLE
ASHA suggests points not contained in space

### ISSUE THREAD

**Issue by vmichals** [Epistimio/orion#393]
**Describe the bug**
When I define the fidelity dimension as fidelity(25,1000,base=2), ASHA proposes 24 for the bottom rung. Do min_resources, max_resources have to be powers of base?

**Expected behavior**
I expected the rungs to be adjusted in some way to match the min/max resources. I don't know the algorithm well, so I might be missing something.

**Steps to reproduce**
Define a search space with fidelity(25,1000,base=2) and use ASHA

**Environment**
 - OS: CentOS Linux release 7.7.1908 (Core)
 - Python version: e.g. 3.6.9
 - Oríon version: develop
 - Database: PickleDB

**Possible solution**
I think the rungs are computed [here](https://github.com/Epistimio/orion/blob/29c0dfc13637aa3add6a57ce585232d65afcc541/src/orion/algo/asha.py#L43)

There seems to be a check if the last element is greater than `max_resources` [here](https://github.com/Epistimio/orion/blob/29c0dfc13637aa3add6a57ce585232d65afcc541/src/orion/algo/asha.py#L52).
Maybe one could add a similar test for the first element not being lower than `min_resources`.

**Comment by Thomsch** [comment]
Thank you for raising this issue. I'll take a look at it with @bouthilx.

**Comment by bouthilx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ASHA suggests points not contained in space](https://trello.com/c/K2Ro4xkR/566-asha-suggests-points-not-contained-in-space)
