### ISSUE TITLE
ASHA promotes unfinished trials

### ISSUE THREAD

**Issue by vmichals** [Epistimio/orion#395]
**Describe the bug**
ASHA promotes trials that are not yet completed in the next lower rung.

**Expected behavior**
From my understanding ASHA should not promote trials that didn't report a result.

**Steps to reproduce**
Use the following minimal dummy experiment script and make it executable:
```python
#!/usr/bin/env python
from orion.client import report_objective
from numpy.random import randn
import time
time.sleep(120) # set this large enough to be able to start multiple workers
report_objective(randn())
# vim: set ts=4 sw=4 sts=4 expandtab:
```
Run multiple (for me it happened with 3-4) workers (`clusterssh` is very convenient for this) with
```bash
orion hunt -c planetgc_orion_config.yaml -n test_asha --worker-max-trials 5 test.py --epochs~'fidelity(1,64,base=2)' --learning-rate~'loguniform(.00001,.01)' --momentum~'uniform(.7,.95)'
```

Fetch trial details with the following python script:
```python
from orion.client import create_experiment
exp = create_experiment(name='test_asha')
print(f"{'STATUS':^10} {'START':^30} {'END':^30} {'FIDELITY':^8} {'PARAMS_HASH':^35}")
print('-'*120)
for trial in exp.fetch_trials():
    print(f"{trial.status:>10} {str(trial.start_time):>30} {str(trial.end_time):>30} {trial.params['/epochs']:>8} {trial.hash_params:>35}")
```

This produces the following output for me:
```
  STATUS               START                           END               FIDELITY             PARAMS_HASH            
------------------------------------------------------------------------------------------------------------------------
 completed     2020-05-25 04:19:12.680012     2020-05-25 04:19:43.317895        1    72227ac933931b34ff548bc8e76edb5a
 completed     2020-05-25 04:19:12.724151     2020-05-25 04:19:43.362414        1    e8e56812294709896f4d063bfeb2d665
 completed     2020-05-25 04:19:13.859707     2020-05-25 04:19:44.524475        2    72227ac933931b34ff548bc8e76edb5a
 completed     2020-05-25 04:19:13.923803     2020-05-25 04:19:44.561748        1    6c69424baa02529ed192c149f3710f61
 completed     2020-05-25 04:17:09.541189     2020-05-25 04:17:40.249103        1    46b411cdecce47ec49da2bcb8785361c
...
```
Note, that the first and third row have the same parameter hash (identical configuration, except the fidelity dimension), but the third trial starts before the first has finished.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python version: e.g. 3.6.9
 - Oríon version: develop
 - Database: PickleDB

**Possible solution**
In [this line](https://github.com/Epistimio/orion/blob/29c0dfc13637aa3add6a57ce585232d65afcc541/src/orion/algo/asha.py#L341) `get_candidates()` only filters out trials that have objective `None`, not those with objective `infinity`, which seems to be the initial objective value for trials.
See PR  #396

**Comment by Thomsch** [comment]
Thank you for the detailed issue. We really appreciate it. We'll get to it very soon.

**Comment by vmichals** [comment]
@bouthilx just helped me find the issue in my config:
The strategy item has to be directly in the experiment section not in the subsection producer!

**Comment by Thomsch** [comment]
Thank for the feedback! We'll update the doc to make it clear 👍

**Comment by bouthilx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ASHA suggests points not contained in space](https://trello.com/c/K2Ro4xkR/566-asha-suggests-points-not-contained-in-space)

**Comment by bouthilx** [comment]
@vmichals I tried to reproduce the issue with the configuration
```yaml
producer:
    strategy: StubParallelStrategy
```
But the strategy was correctly set. Could you confirm if it's still failed on your side? Normally it should work but give you the following exception:
```
WARNING:orion.core.io.resolve_config:(DEPRECATED) Option `producer` is deprecated and will be removed in v0.3. Use instead the option
experiment:
  strategy: StubParallelStrategy
```

**Comment by vmichals** [comment]
Unfortunately, I can't run that experiment right now, but the config that failed for me was:
```yaml
experiment:
    algorithms: 
        asha:
            seed: null
            num_rungs: null
            num_brackets: 4
    producer:
        strategy: StubParallelStrategy
```
You checked the code and told me that the `producer` section should go to the top-level of the config, which worked for me.

**Comment by bouthilx** [comment]
Ah! Got it, thanks!
