### ISSUE TITLE
Implement better authorization method for database

### ISSUE THREAD

**Issue by tsirif** [Epistimio/orion#45]
Regarding authorization, users are currently expected either to provide a compatible URL string in `METAOPT_DB_ADDRESS` environmental variable which can contain `username:password` credentials, or provide them in a `moptconfig.yaml` file under key `database: username: 'asdfa'` and `database: password: 'asdfasfa'`. First one uses environmental variables, second one a plain text file in user's directory. Both of these can be considered unsafe.

We should discuss better ways of requesting user's credential for the database. Perhaps by using Python std module `getpass`. Complications may arise on how to distribute the credentials to multiple processes in perhaps multiple nodes, which can be the general scenario. The reason is that there must be one `MongoClient` (for instance) for each worker, all of these use the same options (and hence credentials), and we would like to request for the credentials once. Perhaps using an *ssh* mechanism for the multi-node case is necessary. I am not very familiar with the issues that can arise here.

So we should discuss and organize a solution that perhaps fits all scenarios, but is not enforced if things are kept in a single local node.

Issue has been raised by @nasimrahaman.

**Comment by lamblin** [comment]
PostgreSQL uses a config file named `.pgpass`, where users can put their credentials, see https://www.postgresql.org/docs/9.3/static/libpq-pgpass.html

I would guess other DB systems have their own way. Can we just rely on them, unless users want to explicitly provide them through metaopt?

**Comment by bouthilx** [comment]
I can't find anything similar for mongodb. The best I can find are hacks to make it alike: http://dbversity.com/password-option-file-in-mongodb/. Problem is it only applies to mongo shell if I understand correctly. 

It seems to me that setting a global config for metopt, which is likely to concern mainly the database, is similar to the .pgpass solution for the credentials and should be just as safe. Problem is we allow passwords in **any** hierarchical level of the configuration. Could we allow it at global level only?

**Comment by nouiz** [comment]
To make the config file safe, the software should assert that the file
permission is only given to the user and nobody else.

Forcing it only at the global level is a good idea, bit not part of the MVP
and if hard to implement, we can just document it well seeing it at non
global place is bad and will be enforced later.

Le lun. 5 mars 2018 17:27, Xavier Bouthillier <notifications@github.com> a
écrit :

**Comment by bouthilx** [comment]
For reference, we agreed on today's meeting that we will fix this issue by allowing users to set the password in the global configuration file only and verify that the file have safe read access (admin, user read/write only) (similar to safety concept for .ssh/). 

This issue however won't be fixed now and we will only document best practices guides. We'll see later on when we have time to fix this.

**Comment by bouthilx** [comment]
We are migrating to a different storage backend so these tests probably won't ever be needed.
