### ISSUE TITLE
No module named `readline` -- this package is not available in Windows 10

### ISSUE THREAD

**Issue by josephdviviano** [Epistimio/orion#454]
**Describe the bug**

When importing`orion.client` on windows 10 (using miniconda Python 3.8.5),

```
    from orion.core.io.interactive_commands.branching_prompt import BranchingPrompt
  File "C:\Users\vivij\Miniconda3\envs\cdpq\lib\site-packages\orion\core\io\interactive_commands\branching_prompt.py", line 18, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

**Expected behavior**
The module should import without error.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.8.5
 - Oríon version: 0.1.8
 - Database: Unknown / NA

**Possible solution**

It looks like `pyreadline` is the windows friendly alternative to `readline` for windows [according to this post](https://stackoverflow.com/questions/51157443/pythons-readline-module-not-available-for-windows) (ugh). Some conditionals in the import statements should do the trick. I can submit a pull request if this sounds good to the team.

**Comment by bouthilx** [comment]
pyreadline does not seam to be maintained anymore. I'm also a bit concerned about adding code that we cannot test as we do not have windows virtual machines on Travis.

If you install pyreadline, would it work out of the box? Also, I'm not familiar with windows but isn't there an integration with ubuntu now that would enable using readline in the ubuntu terminal?

**Comment by josephdviviano** [comment]
I patched my local version of `branching_prompt.py` with the following (after `pip install readline`):

```
if os.name == 'nt':
    from pyreadline import Readline
    readline = Readline()
else:
    import readline
```

I see your concern with the package not being maintained (also, it is very ugly that `readline` isn't already cross platform).

I'm also not super familiar with windows, I am just using a windows laptop for a project for security reasons. There is a Ubuntu integration that would likely circumvent this problem, however, I'm running in the more traditional git-bash type environment with a native windows miniconda install.

**Comment by bouthilx** [comment]
Using windows for security reasons? :sweat_smile: :stuck_out_tongue_winking_eye: 

If that works fine for you locally I would avoid adding the conditional import in Oríon's core since we cannot test it at the moment and there would be no pyreadline in the dependencies (the user must install it manually).

**Comment by josephdviviano** [comment]
Haha it's a company-issued laptop, it's what makes *them* feel safe 😆 

I'm happy with my solution here, I can understand why you wouldn't want to put this patch in the code all considered.

**Comment by bouthilx** [comment]
Alright. So I will close this issue and tag it with windows. If we ever decide to support windows officially and setup a CI for windows we will be able to find back this issue based on the tag.
