### ISSUE TITLE
How to insert trials in an experiment?

### ISSUE THREAD

**Issue by JakeColor** [Epistimio/orion#683]
Question.

How can I populate an experiment with trial parameters and results from a dataset of training runs?

## Context
My colleagues & I have a pandas DataFrame of grid search results extracted from W&B, and are trying to leverage orion's `experiment.plot.partial_dependencies` functionality.

Our DataFrame looks like:

|name                |hparam1|hparam2|hparam3|hparam4|hparam5  |hparam6  |loss    |
|--------------------|----------|----------|------|-----|-----|------|---------------------|
|legendary-pond-77   |128       |64        |2     |128  |0.01 |1e-06 |0.001|
|solar-eon-76        |128       |32        |2     |128  |0.01 |1e-06 |0.0012|
|sunny-energy-75     |128       |16        |2     |128  |0.01 |1e-06 |0.002 |

## What We've Tried So Far
```python
experiment = create_experiment('grid-search-{wandb_project}-2021-10-18-v2', space=hparam_spaces) # hparam_spaces is a set of "choices"

for index, record in runs.iterrows():
    params = record[hparam_cols].to_dict()
    loss = {'name': loss_col, 'type': 'objective', 'value': record[loss_col]}
    experiment.insert(params=params, results=loss)
```

But get the following error (full traceback below):
 `type object argument after ** must be a mapping, not str`

We've also tried passing `Value` instances directly:
```python
from orion.core.worker.trial import Trial
v = Trial.Value()
v.name = loss_col
v.type = 'objective'  # error: ValueError: Given type, objective, not one of: ()
v.value = 1
```

What is the best way to achieve our goal?

**Comment by bouthilx** [comment]
Hi Jake!

You were very close to getting it working! :) The results argument must be a list. So in your case you would make the call like this `experiment.insert(params=params, results=[loss])`.

I will clarify the documentation. Let me know if you have other issues!
