### ISSUE TITLE
Support for nesting in config yaml files

### ISSUE THREAD

**Issue by lebrice** [Epistimio/orion#768]
(Somewhat of a prerequesite to  #767, I think)
Found this while trying the config file alternative to passing the params from the command-line, because of #769 

Config files with hierarchical values aren't currently supported:

my_sweep.yaml
```yaml
b_optim:
  lr: 'loguniform(1e-6, 0.5, shape=4)'
debug: True
```

```console
$ orion hunt -n my_exp python main.py --config my_sweep.yaml
Error: No prior found. Please include at least one.
```

**Comment by bouthilx** [comment]
Oh, it should work for config files. As documented [here](https://orion.readthedocs.io/en/stable/user/searchspace.html#configuration-file) you need to use the template `'orion~loguniform(1e-6, 0.5, shape=4)'`. Can you please confirm if that resolves the issue?

**Comment by lebrice** [comment]
I realize now that I assumed that passing yaml config files worked one way, but it's totally different. Closing this.
