### ISSUE TITLE
Cannot execute workon inside a subprocess

### ISSUE THREAD

**Issue by bouthilx** [Epistimio/orion#807]
The Runner class tries to protect trial execution from sigint and sigterm signals using `signal.signal` but this fails when the Runner is being executed inside a child process. 

In some cases a user may need to execute the Runner in a child process. It should be possible to do so although the protection would be lost. We should warn about the sigint and sigterm instead of crashing in such situation.

**Comment by Delaunay** [comment]
Should be resolved now
