### ISSUE TITLE
Numpy warnings when running tests

### ISSUE THREAD

**Issue by lebrice** [Epistimio/orion#877]
Warnings about non-tuple indexing or np.object dtypes happen during tests. Would be nice to get rid of those.

**Comment by Delaunay** [comment]
` np.object dtypes` were fixed in https://github.com/Epistimio/orion/commit/d04c6ab9c484c55bd601fc200eae7ad7c93784af

**Comment by Delaunay** [comment]
I see only one numpy warning remaining but it is outside of Orion. Maybe we can close this ticket ?

```
  tests/unittests/client/test_runner.py::test_runner_inside_dask
    /home/runner/work/orion/orion/.tox/py-all/lib/python3.10/site-packages/bokeh/core/property/primitive.py:37: DeprecationWarning:
    
    `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
    ```
   
I opened https://github.com/Epistimio/orion/issues/1044 to review all warnings a try to reduce the amount to make them a bit more useful
