### ISSUE TITLE
Refactor / remove `spy_phase` of BaseAlgoTests

### ISSUE THREAD

**Issue by lebrice** [Epistimio/orion#884]
This `spy_phase` doesn't seem very intuitive to me. It makes the tests much more opaque than they need to be.

There are other ways of creating fixtures on classes dynamically, for instance by setting a class attribute in `__init_subclass__`. This would be preferable, in my opinion. 

Here is what I suggest to change:
- Standardize the use of the  `phases` class attribute in all algo tests
- Remove the following:
    - spy_phase
    - spy_attr
    - recursive_getattr
    - recursive_setattr
    - methods_with_phase
    - (etc etc)
- Add a new `phase` fixture that gets parametrized with the value from `cls.phases` and yields the current phase.
- (a bit unsure about this one): Add a new `algo` fixture that subclasses can overwrite that uses this `phase` fixture, OR
- Make `create_algo` observe all the initial trials required for the current phase before returning the algo instance.
    - It might be a good idea to only create one such instance per phase, and then just provide deepcopies to each individual tests, just to make the tests a bit quicker to run?

Any thoughts @bouthilx ?

**Comment by bouthilx** [comment]
I think these are very good ideas. It's not clear to me what you mean with the incremental phases compared to the current phases but that seems to be just a minor detail. Reducing the running time of the tests by sharing the initial algo state would be quite helpful indeed. That will only work if the algo is copied with all internal state properly (like some algos may use global RNG in which case they need to be reseeded). That's pretty bad but cannot be avoided when wrapping some libraries...

**Comment by lebrice** [comment]
Indeed you're right about the incremental phase thing being confusing. I'll edit the post above.

**Comment by lebrice** [comment]
> Reducing the running time of the tests by sharing the initial algo state would be quite helpful indeed

Yeah I was just thinking about it more, Ideally, the fixture would parametrize the test such that the algo state after, say, `10` trials is kept,  and then reused to create the algo state after 20 trials, rather than re-creating a new algo from scratch, and making it observe 20 trials. However, this would require each test to be run through all phases in-sequence before moving to the next test, which isn't how pytest currently does it: It goes through one phase for all tests, then another phase for all tests, etc.
