### ISSUE TITLE
Support storage checkpointing and restore

### ISSUE THREAD

**Issue by bouthilx** [Epistimio/orion#953]
Users need a way to checkpoint their current storage and restore it. This would also allow migrating from one database backend to another, for example checkpointing from pickleddb, and then loading the checkpoint into mongodb. The easiest way to support this would be to save the checkpoint into a pickleddb. The restoration would be the trickiest part, as we need to ensure there are no collisions, and that the id references between experiments and trials are conserved even though the ids will need to change to avoid collisions with existing data in the storage.

`orion db dump --config orion_config.yaml --exp experiment`
`orion db load --config orion_config.yaml --exp experiment dump.pkl`

`--exp` would be an optional argument to select only a subset of the data.

**Comment by lavoiems** [comment]
Would --config also be an optional argument? I could have run several experiments each with different configs and still want to archive everything.

**Comment by bouthilx** [comment]
Yes, config here would be to specify another storage than the one in global configuration, if necessary.

**Comment by bouthilx** [comment]
If there are experiment ID conflicts during `load`, we could offer to `ignore`, `overwrite` or `bump version of incoming experiment`. When overwritting, should we deleting the prior trials? :thinking:
