### ISSUE TITLE
Track execution time of trials

### ISSUE THREAD

**Issue by bouthilx** [Epistimio/orion#98]
We have `submit_time`, `start_time` and `end_time`, but that doesn't tell how long a trial have been executed if there was interruptions/suspensions in its lifetime.

**Comment by DatCorno** [comment]
Should we track interruption points? I feel like this could also be useful with checkpoints.

**Comment by bouthilx** [comment]
We now have heartbeats which solves issue for automatic failover from reserved to interrupted. For execution time maybe to should not be the role of Oríon.
